"""empty message

Revision ID: 05950468439e
Revises: 3ed85399d9db
Create Date: 2026-02-24 19:03:19.518404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05950468439e'
down_revision = '3ed85399d9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_move_out_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('actual_move_out_date')

    # ### end Alembic commands ###
