"""empty message

Revision ID: 3ed85399d9db
Revises: a9ed2b8870a4
Create Date: 2026-02-23 15:44:25.965907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed85399d9db'
down_revision = 'a9ed2b8870a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exitedBeforeLeaseEnd', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('exitedBeforeLeaseEnd')

    # ### end Alembic commands ###
