"""fresh start

Revision ID: 53467aa83121
Revises: 
Create Date: 2026-02-19 15:29:21.679493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53467aa83121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id')
    )
    op.create_table('towers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('towers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_towers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_towers_locality'), ['locality'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_roles'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('tenant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_type', sa.Enum('STUDENT', 'WORKING', name='tenant_types'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('college_name', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('id_proof_type', sa.Enum('PAN', 'AADHAAR', name='id_proof_types'), nullable=False),
    sa.Column('id_proof_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tower_amenities',
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('tower_id', 'amenity_id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('flat_number', sa.String(length=10), nullable=False),
    sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('flat_type', sa.Enum('1BHK', '2BHK', '3BHK', name='flat_types'), nullable=False),
    sa.Column('furnishing', sa.Enum('Fully Furnished', 'Fully Furnished AC', 'Semi-Furnished', name='furnishing_types'), nullable=False),
    sa.Column('balcony_type', sa.Enum('Road Facing Balcony', 'Without Road Facing Balcony', 'Double Balcony Road facing', 'Triple Balcony No Road', 'Triple Balcony Road facing', 'Without Balcony', 'Without Road Facing Double Balcony', 'Double Balcony', name='balcony_type'), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('facing_direction', sa.Enum('East', 'West', 'North', 'South', 'North-East', 'North-West', 'South-East', 'South-West', name='facing_directions'), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_available_from'), ['available_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_balcony_type'), ['balcony_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_flat_type'), ['flat_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_furnishing'), ['furnishing'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_parking'), ['parking'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_rent'), ['rent'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_unit_code'), ['unit_code'], unique=True)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='booking_status'), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=False),
    sa.Column('lease_start', sa.Date(), nullable=True),
    sa.Column('lease_end', sa.Date(), nullable=True),
    sa.Column('rent_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_unit_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))

    op.drop_table('bookings')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_unit_code'))
        batch_op.drop_index(batch_op.f('ix_units_rent'))
        batch_op.drop_index(batch_op.f('ix_units_parking'))
        batch_op.drop_index(batch_op.f('ix_units_is_active'))
        batch_op.drop_index(batch_op.f('ix_units_furnishing'))
        batch_op.drop_index(batch_op.f('ix_units_flat_type'))
        batch_op.drop_index(batch_op.f('ix_units_balcony_type'))
        batch_op.drop_index(batch_op.f('ix_units_available_from'))

    op.drop_table('units')
    op.drop_table('tower_amenities')
    op.drop_table('tenant_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('towers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_towers_locality'))
        batch_op.drop_index(batch_op.f('ix_towers_code'))

    op.drop_table('towers')
    op.drop_table('images')
    op.drop_table('amenities')
    # ### end Alembic commands ###
